### ISSUE TITLE
Only works on Windows

### ISSUE THREAD

**Issue by ramsburytech** [Maven85/plugin.video.dazn#1]
I've tested this on my MacBook, FireStick and Windows 10 Kodi installs but only the Windows one works.

All have the same Kodi version installed and had the original Kodi repo version of Dazn installed, I just copied this versions files over the top.

**Comment by Maven85** [comment]
Without additional information, e.g. debug log, I can not help you.

**Comment by arthemis841** [comment]
It works for me on firestick. Try to uninstall the older version, then install the new one from zip

**Comment by ramsburytech** [comment]
The latest version 1.38 seems to work now.
